# nixpacks.toml

[phases.setup]
nixPkgs = ["bun", "nodejs_25", "ffmpeg", "wget"]
aptPkgs = ["git"]
 
[phases.install]
cmds = ["bun install --frozen-lockfile"]

[phases.build]
cmds = ["echo 'Building assets...'"]

[start]
cmd = "bun run src/index.ts"